name: Release-beta

# action qui déclenche la CI #
on:
  push:
    branches:
    - main

# Jobs du workflow #
jobs:
  # premier job : get version à partir d'un autre workflow #
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with: 
      release-branches: '^(main)$'

  # deuxième job : build du projet en plusieurs étapes  #
  build:
    # le build doit tourner sur la dernière version d'ubuntu #
    runs-on: ubuntu:latest
    # étapes #
    steps:
      # action qui clone le dépot dans l'environnement  de travail du workflow pour pouvoir executer des tests ou des scripts dessus #
      - name: step checkout
      - uses: actions/checkout@v2

      # action qui récupère le numero de la version du projet #
      - name: step install beta
        uses: actions-rs/toolchain@v1
        with:
            toolchain: beta
            override: true
            components: rustfmt, clippy

      # action qui verifie la compilation des paquets de cargo #
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      # action qui build le projet #
      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          
      # action qui installe trunk car il n'est pas installé dans mon environnement de travail #
      - name: Install Trunk
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export PATH="$HOME/.deno/bin:$PATH"
          deno install -qAf --unstable https://deno.land/x/trunk@latest/cli.ts

      # action qui execute trunk #
      - name: Run Trunk
        run: trunk build
        
    # troisième job : create-release #
    needs:
      create-release:
    
    

      

      


      
