name: Release-beta

# action qui déclenche la CI #
on:
  push:
    branches:
    - main

# Jobs du workflow #
jobs:
  # premier job : get version à partir d'un autre workflow #
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with: 
      release-branches: '^(main)$'

  # deuxième job : build du projet en plusieurs étapes  #
  build:
    # le build doit tourner sur la dernière version d'ubuntu #
    runs-on: ubuntu:latest
    # étapes #
    steps:
      # action qui clone le dépot dans l'environnement  de travail du workflow pour pouvoir executer des tests ou des scripts dessus #
      - name: step checkout
      - uses: actions/checkout@v2

      # action qui récupère le numero de la version du projet #
      - name: step install beta
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            target: wasm32-unknown-unknown
          
      # action qui installe et execute trunk #
      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0

      # build du projet avec trunk #
      - name: build with trunk
        env:
         VERSION: "${{ needs.get-version.outputs.version }}"
        run: trunk build --release
      - uses: actions/upload-artifact@v4
        with:
         name: Chemin
         path: ./dist
        
  # troisième job : create-release #
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      

      
    

      

      


      
